* Flowjs / spacemacs interation

** Dependencies:
*** Emacs packages
  - company-flow
  - popup.el

Popup.el should already be a dependency in spacemacs default config. For company-flow, manually add in dotspacemasc/layers, eg:

#+begin_src emacs-lisp
dotspacemacs-additional-packages '(company-flow)
#+end_src

*** Spacemacs layers:
  - auto-completion (for company)
  - syntax-checking (for flycheck)
  - react for react-mode
  - javascript for js2-mode

*** JS tooling, see example folder:
  - local flow (partial global support)
  - local or global eslint with babel-eslint

**  Install:
Load flow.el file and call (init-flowjs) from dospacemacs/user-config, eg:

#+begin_src emacs-lisp
(load-file "~/config/spacemacs/flow.el")
(init-flowjs)
#+end_src

**  Testing:
1. Clone repo, cd into example folder and run npm install to get flow and eslint:

#+begin_src bash
git clone git@github.com:tbinetruy/config.git
cd config/spacemacs/flow/example
npm install
#+end_src

2. Reload spacemacs config by restarting it or pressing <SPC> f e R

3. start react-mode or js2-mode

** Flow semantic autocomplete
Autocomplete is ran through company-flow [0]. If you have the spacemacs auto-completion layer enabled [1], flow suggestions will show up in the Company [2] autocomplete popup.

[0] https://github.com/aaronjensen/company-flow
[1] http://spacemacs.org/layers/+completion/auto-completion/README.html
[2] http://company-mode.github.io/

** Flow type linting
Linting is ran through flycheck. As of right now, the only limitation is that flow linting only occurs on file saves (but eslinting still occurs as you type). Installing the syntax-checking spacemacs layer [1] will install flycheck as a dependency.

[0] http://www.flycheck.org/en/latest/
[1] http://spacemacs.org/layers/+checkers/syntax-checking/README.html


** Key bindings
All keybindings are preceeded by: *<SPC> m f*.

| key binding | action                                  |
|-------------+-----------------------------------------|
| t           | flow type in popup above cursor         |
| a           | auto complete suggestions in new window |
| d           | def location in new window              |
| f           | flow status in new window               |
| s           | flow suggestions in new window          |




